name:                molecule
version:             0.1.0.0
github:              "wurthel/molecule"
license:             BSD3
author:              "Vusal Salmanov"
maintainer:          "salmanov.vh@gmail.com"
copyright:           "2020 Vusal Salmanov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/molecule#readme>

dependencies:
- base >= 4.7 && < 5
- strict
- lens
- hmatrix
- process
- linear
- vector
- matrix
- mtl
- containers
- directory
- random

library:
  source-dirs: src

executables:
  molecule-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - molecule

tests:
  molecule-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - molecule
